-   name: Asegurar que está instalado el software necesario para el playbook en Debian/Ubuntu
    include_tasks: "utils/install.{{ ansible_facts['os_family'] }}.yaml"
    vars:        
        packages: {{ apacheInternal.baseDependecies }}  
        update: True
    tags:
        - mandatory

-   name: Asegurar que está instalado el software necesario para las apps que ponga en apache
    include_tasks: "utils/install.{{ ansible_facts['os_family'] }}.yaml"
    vars:        
        packages: {{ apache.dependencies }}
        update: False
    tags:
        - pre-instalacion
#curl
#nginx:80