-   name: Asegurar que apache quede configurado como yo quiero
    notify: REINICIO_REQUERIDO
    copy:
        src: resources/httpd.conf
        dest: "{{ apacheInternals.etcDir}}"
    tags:
        - configuracion

-   name: Asegurar que están los virtual host que quiero #documentRoot
        # {{ item }}
    template:
        src: resources/virtualhost.conf
        dest: "{{ apacheInternals.sitesDir}}"
    loop: "{{ virtualhosts | default( [] ) }}"
    notify: REINICIO_REQUERIDO
    tags:
        - configuracion
    
-   name: Asegurar que apache tiene su servicio
    tags:
        - configuracion

-   name: Asegurar que apache tiene su servicio configurado para arranque automatico
    tags:
        - configuracion

-   name: Asegurar que apache tiene su servicio corriendo # START
    register: estado_servicio # Sustantivo
    tags:
        - configuracion

-   name: Asegurar que los puertos del apache quedan abiertos en el firewall local
        # {{ item.ports }}
    loop: "{{ virtualhosts | default( [] ) }}"
    tags:
        - configuracion
    