-   name: Asegurar que apache quede configurado como yo quiero
    notify: REINICIO_REQUERIDO
    copy:
        src: resources/httpd.conf                          # Ruta del host donde se ejecuta ansible
        dest: "{{ apacheInternals.etcDir }}/httpd.conf"    # Ruta del host contra el que se ejecuta ansible
    tags:
        - configuracion

-   name: Asegurar que están los virtual host que quiero #documentRoot
        # {{ item }}
    template:
        src: resources/virtualhost.conf.j2
        dest: "{{ apacheInternals.sitesDir }}/{{ item.appName }}.conf"
    loop: "{{ virtualhosts | default( [] ) }}"
    notify: REINICIO_REQUERIDO
    tags:
        - configuracion
    
-   name: Asegurar que apache tiene su servicio
    tags:
        - configuracion

-   name: Asegurar que apache tiene su servicio configurado para arranque automatico
    tags:
        - configuracion

-   name: Asegurar que apache tiene su servicio corriendo # START
    register: estado_servicio # Sustantivo
    tags:
        - configuracion

-   name: Asegurar que los puertos del apache quedan abiertos en el firewall local
        # {{ item.ports }}
    loop: "{{ virtualhosts | default( [] ) }}"
    tags:
        - configuracion
    