-   name: Asegurar que apache quede instalado en Debian y derivados # Ian Deborah
    include_tasks: "utils/install.{{ ansible_facts['os_family'] }}.yaml"
    vars:        
        packages:
            - name: httpd
              version: {{ apache.version }}
        update: False
    tags:
        - instalacion

-   name: Asegurar que están instalados los modulos requeridos de apache #modules
        # {{ item }}
    loop: "{{ apache.modules | default( [] )}}"
    notify: REINICIO_REQUERIDO
    tags:
        - instalacion
        - configuracion


-   name: Asegurarme que mi app quede instalada #documentRoot
        # {{ item }}
    loop: "{{ apache.virtualhosts | default( [] )}}"
    notify: REINICIO_REQUERIDO
    tags:
        - instalacion
        - configuracion

