-   name: Asegurar que apache quede instalado en Debian y derivados # Ian Deborah
    when: *esDebian
    tags:
        - instalacion
    
-   name: Asegurar que apache quede instalado en Redhat y derivados
    when: *esRedhat
    tags:
        - instalacion

-   name: Asegurar que están instalados los modulos requeridos de apache #modules
        # {{ item }}
    loop: "{{ apache.modules }}"
    notify: REINICIO_REQUERIDO
    tags:
        - instalacion
        - configuracion


-   name: Asegurarme que mi app quede instalada #documentRoot
        # {{ item }}
    loop: "{{ apache.virtualhosts }}"
    notify: REINICIO_REQUERIDO
    tags:
        - instalacion
        - configuracion
