apache:                 
    version:                latest
    user:                   apache
    virtualhosts:           
        -   domain:         localhost
            documentRoot:   /home/apache/app
            ports:
                            - 80
            appRepo:        https://github.com/IvanciniGT/webEjemploAnsible
    dependencies:           
                            - # Es una dependencia
                                name: php
                                version: latest
                            - # Es una dependencia
                                name: git
                                version: 2.17.1
                                #repo
                                #key
                                #upgrade: false # Vaor por defecto
    modules:                
                            - mod_php
