apache:                 
    user:                   apache
    virtualhosts:           
        -   domain:         localhost
            documentRoot:   /home/apache/app
            ports:
                            - 80
            app:            https://github.com/IvanciniGT/webEjemploAnsible
    dependencies:           
                            - php
    modules:                
                            - mod_php