# Playbook
-
    # Entornos en los que voy a ejectar este playbook
    hosts: all # mipc localhost
    # Esto es por defecto
    gather_facts: False
    #...
    vars:
        generateIfNotExists: True # A nivel de inventario... en cada maquina o grupo
        regenetateIfChanged: True
    
    # Cómo se sacan los gather_facts? Internamente... cual es el procedimiento?
    tasks:
        -   name: Consultar si el host está en known_hosts
            delegate_to: localhost
            shell: 
                cmd: |
                    ssh-keygen -F {{ ansible_host }}
            when: ansible_connection == 'ssh'
            register: entrada_existente
            changed_when: False
            failed_when: False
        
        -   name: "Debugging"
            debug:
                msg: "{{ entrada_existente }}"
                
        -   name: El host no existe en known_hosts
            block:  
                -   name: Abortar si no lo tengo que crear
                    delegate_to: localhost
                    debug:
                        msg: "El host: {{ inventory_hostname }} ({{ ansible_host }}), no está dado de alta en known_hosts. Abortando."
                    failed_when: True
                    when: not generateIfNotExists
                    
                # Si llego a este punto, que significa? Tengo que crearla
                -   name: Creamos entrada en known_hosts
                    delegate_to: localhost
                    shell: ssh-keyscan -H {{ ansible_host }} >> ~/.ssh/known_hosts

            when: entrada_existente.rc is defined and entrada_existente.rc != 0

        -   name: El host si existe en known_hosts
            block:  
                # Comprobar si el valor me encaja con el actual
            when: entrada_existente.rc is defined and entrada_existente.rc == 0
            
            # meta: end_play. Aborta el play
    # 1º Comprobar si está:
        # 2º Si lo que hay es lo mismo que lo que deberia tener
                # 3ª Si lo es... TODO OK. NADA. changed: NO
                # 4º Si no lo es? 
                    # AQUI HA PASADO ALGO? 
                        # Puede ser normal o no? Al menos debería avisar de alguna forma
                        # En funcion de una variable regenero o no
                            # Si no regenero? ERROR
                            # Si regenero:
                                # Eliminar la vieja
                                # ssh-keygen -R {{ ansible_host }} 
                                # Poner la nueva

    
    # MONTARLO Y CONVERTIRLO EN UN ROLE
    
    
        -   name: Comprobación
            setup:
                gather_subset:
                  - '!all'
    